### PR TITLE
chore: upgrade deps

### PR DESCRIPTION
**Pull request by zaibon**
Upgrade dependencies to the latest versions.
This solves the issue with the deprecation of the `set-env` function from GitHub Actions.

### CODE REVIEW

**Comment by daaku** [comment]
Hi, thanks for this PR. In debugging the failed action I decided to replace `node` with `bash`.

If possible, try PR #69 and let me know if it works for you. I'm not using this any longer, but the minimal test seems to indicate things are still working as intended.

**Comment by zaibon** [comment]
I also struggled a bit to get the action to pass, but I managed to do it by using an older version of node. You can see the commit that solved the problem at https://github.com/zaibon/go-buildinfo/commit/2ff4ebe5d29fe238d301404ef0a4fb075bc61b7d

**Comment by daaku** [comment]
Ah, I wonder why that didn't reflect in the run on this PR here. In any case, I can wait for you to test PR #69 or merge it and you can test it after it's tagged?

**Comment by daaku** [comment]
I've tested that version tagged `v2.0.1` and it seems good.

**Pull request closed without merging**
